server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: BANK APPLICATION
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
